baseURL = "/"
title = "Racklet"
enableRobotsTXT = true
enableEmoji = true

# Language configuration
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

# Markup settings
# Ref: https://gohugo.io/getting-started/configuration-markup#goldmark
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "dracula"
[markup.parser]
autoHeadingID = true
autoHeadingIDType = "github"

# Provide .LastMod values
enableGitInfo = true

[languages]
[languages.en]
languageName = "English"
languageCode = "en-us"
time_format_default = "2006-01-02"
time_format_blog = "2006-01-02"

[[menus.main]]
name = "Blog"
url = "/blog"
weight = 10

[[menus.main]]
identifier = "docs"
name = "Docs"
weight = 20

[[menus.main]]
name = "Racklet"
parent = "docs"
url = "https://docs.racklet.io"
weight = 1

[[menus.main]]
name = "Community"
url = "/community"
weight = 30

[[menus.main]]
identifier = "project"
name = "Project"
weight = 40

[[menus.main]]
name = "Code of Conduct"
parent = "project"
url = "https://github.com/racklet/racklet/blob/main/CODE_OF_CONDUCT.md"
weight = 1

[[menus.main]]
name = "Community"
parent = "project"
url = "https://github.com/racklet/racklet/blob/main/COMMUNITY.md"
weight = 20

[[menus.main]]
name = "Contributing"
parent = "project"
url = "https://github.com/racklet/racklet/blob/main/CONTRIBUTING.md"
weight = 30

[params]
description          = "Open Source Scale Model of a Data Center using Raspberry Pis."
copyright            = "The Racklet authors"
github_repo          = "racklet/racklet"
github_website_repo  = "racklet/racklet.io"
slack                = "https://osfw.slack.com/messages/racklet/"
twitter              = "https://twitter.com/kubernetesonarm/"
# linkedin             = ""
# mailing_list         = ""
# youtube              = ""
# support              = "/support"
rss                  = "/blog/index.xml"
font_awesome_version = "5.9.0"

notification = """
📣 **Racklet is a very early-stage project. If you want to get involved, join the [`#racklet`](https://osfw.slack.com/messages/racklet) channel in the [OSFC Slack](https://slack.osfw.dev/).**
"""

[params.logos]
navbar = "racklet_transparent.png"
hero   = "racklet_transparent.png"
footer = "racklet_transparent.png"

[[params.fonts]]
name  = "Montserrat"
sizes = [300,400,600,700]
type  = "sans_serif"

# Main hero element
[params.main]
# title    = "Alternative title"
subtitle = "Open source scale-model of Data Centers using commodity compute like Raspberry Pis."

[[params.main.buttons]]
text  = "Get started"
color = "warning"
url   = "https://docs.racklet.io/get-started/"

[[params.main.buttons]]
text = "Learn more"
url  = "https://docs.racklet.io"

# Overview hero element
[params.overview]
title   = "Overview"
summary = """
Racklet is a fully-integrated, miniature server rack. Racklet aims to inspire their users to explore how modern,
advanced server architectures work in practice, in a tangible and educational way. With the new-found knowledge
and inspiration, the user may apply their modernization skills on traditional server infrastructure, which
improves the status quo and pushes the industry forward. <br/><br/> The following are the core values of the project: 
"""

## Overview features

[[params.overview.features]]
icon   = "fas fa-code fa-3x"
header = "Security-first"
text   = """
We aspire to improve the status quo of "secure-by-default" solutions and concepts available, by using
e.g. [Rust](https://www.rust-lang.org/), [LinuxBoot](https://www.linuxboot.org/) and [TUF](https://theupdateframework.io/).
We challenge some security norms in the industry and move past e.g. insecure protocols like [TFTP](https://en.wikipedia.org/wiki/Trivial_File_Transfer_Protocol).
The design methodologies "Defense in Depth" and "Least Privilege" will be applied.
"""

[[params.overview.features]]
icon   = "fab fa-git-square fa-3x"
header = "Declarative"
text   = """
Declarative management using e.g. [YAML](https://yaml.org) and [Git](https://git-scm.com/) is prominent in the cloud native space, but not
equally in the embedded and firmware space. We believe declarative APIs are very useful and powerful,
as they allow for observe-diff-act reconciliation loops. Consistent Kubernetes-style APIs will be used
across the stack.
"""

[[params.overview.features]]
icon   = "fas fa-drafting-compass fa-3x"
header = "Open Source"
text   = """
Racklet is 100% open source software and hardware. Anyone can contribute, improve,
fork and access the project. We want to bring innovation forward e.g. by publishing and
using open (source) APIs, sharing code freely, and collaborating with fellow community members. 
"""

[[params.overview.features]]
icon   = "fas fa-robot fa-3x"
header = "Accessible"
text   = """
Only use commonly available components that can be aquired in most parts of the world in a frictionless
manner. For non-off-the-shelf casing and PCBs, we provide 3D-printable designs and easily reproducible
schematics, respectively.
"""

[[params.overview.features]]
icon   = "fas fa-box-open fa-3x"
header = "Upgradable"
text   = """
The modularity of the system should allow that individual pieces of the system (e.g. compute,
storage, network switches, power supplies) should be upgradable without having to disrupt the
rest of the rack, or disregard existing, functioning parts. This will minimize E-waste produced over time.
"""

[[params.overview.features]]
icon   = "fas fa-cube fa-3x"
header = "Extensible"
text   = """
The hardware, software, and APIs all strive to be as modular and extensible as possible.
We want to follow the Unix philosophy to allow for portability between e.g. different hardware
modules implementing the same interfaces, or extensibility where the user demands custom features.
"""

# Community hero element
[params.community]
title = "Community"
summary = """
The Racklet project aspires to engage a diverse set of people in the open source world, working
towards a common goal of making data center software and hardware more accessible and secure.
"""

[[params.community.highlights]]
title = "GitHub Discussions"
icon = "fab fa-github"
text  = """
We'd love to see you collaborate to this project! No contribution is too small, we value all input and perspectives.

Join the conversation on [GitHub](https://github.com/racklet/racklet).
"""

[[params.community.highlights]]
title = "Slack"
titleBgColor = "slack-green"
icon = "fab fa-slack"
text  = """
If you want to talk to the Racklet team and community in real-time, join us on Slack. This is a great way to get to know everyone.

[Get an invite](https://slack.osfw.dev), and [go to the `#racklet` channel](https://osfw.slack.com/messages/racklet)
"""

[[params.community.highlights]]
title = "Official Documentation"
titleBgColor = "info"
icon = "fas fa-book"
text  = """
In order to stay up to date with how to use the latest source code available, check out the official documentation.

[Go to the Racklet documentation site](https://docs.racklet.io)!
"""
